### ISSUE TITLE
502 after install: some tinkering that makes it work!

### ISSUE THREAD

**Issue by nazmifr** [YunoHost-Apps/ethercalc_ynh#18]
Hi,
I have yunohost on an ARM single board, the install went smoothly but I'd get 502.

I installed the testing version, the normal branch got me 502 also before I moved to testing.

I dug a bit, with ``` service ethercalc status```

For some reason:
- the npm dependencies of ethercalc were not installed (zappajs j and other dependencies were missing), I had to do

```
cd /var/www/ethercalc
npm install
(maybe even npm install ethercalc)
```

- then it was about socialcalc and i had to 

``` 
cd node_modules/socialcalc
ln dist/SocialCalc.js SocialCalc.js
```

The main page is working, I just have a small issue with what the service status says, that looks like a bug, this /path/prefix thing

```
● ethercalc.service - Ethercalc, the collaborative spreadsheet editor.
   Loaded: loaded (/etc/systemd/system/ethercalc.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-01-06 18:38:13 GMT; 1h 6min ago
 Main PID: 3897 (node)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/ethercalc.service
           └─3897 node /var/www/ethercalc/bin/ethercalc --host 127.0.0.1 --port 8095 --expire 0 --polling --basepath /path/prefix
```

After I had installed everything and created the symbolic link, i just had to do ```service ethercalc start``` and It worked!!!

Please people who know how to edit the installer script, make it work for ynh because there is no real spreadsheet tool available without tinkering and that's really useful to avoid gdocs

**Comment by ericgaspar** [comment]
I finally had the time to work a bit more on Ethercalc. If you want to test... It should be working on master branch now.
