### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by feydreva** [YunoHost-Apps/ethercalc_ynh#5]
During install I get the following error : 

E: Package 'nodejs-legacy' has no installation candidate
E: Unable to locate package npm

I m running Yunohost on : 
# cat /etc/*-release

PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"

**Comment by zamentur** [comment]
Thanks for your issue, I check that.

**Comment by feydreva** [comment]
Hello, 

I tried again on a clean install of Debian 8 and Yunohost with no issue.

**Comment by julienmalik** [comment]
Just installed today (on jessie), the installation works fine (even if the app fails at runtime)
