### ISSUE TITLE
502 bad gateway 

### ISSUE THREAD

**Issue by feydreva** [YunoHost-Apps/ethercalc_ynh#6]
Hello, 

I install it, without error, and now I have 502 bad gateway error.

On the etherpad.conf, is it normal to have no Alias ? no path to the /var/www ??
location /calc/ {
       rewrite                ^/calc$ /calc/ permanent;
       proxy_pass             http://localhost:8000/;
       proxy_set_header       Host $host;
       proxy_buffering off;
       include conf.d/yunohost_panel.conf.inc;
}

also the location of the files is /var/www/ethercalc/node_modules/ethercalc

maybe something there ?

**Comment by zamentur** [comment]
It is normal, ethercalc is a nodejs apps, so it works with a proxy: nginx don't serve directly the file.

Maybe your ethercalc is not running ?
Try: service ethercalc restart

**Comment by stephLH** [comment]
I have the same problem on yunohost 2.5.
I also executed `service ethercalc restart`.

**Comment by julienmalik** [comment]
confirmed here
see #7
